

heartbeat:
  port: 20222
  region: "北京"
  duration: 2
  resources: 5


http:
  address: "0.0.0.0:20222"                                    #本服务host
  port: 20222                                               #本服务端口
  readTimeout: 5000                                          #fasthttp client完整响应读取(包括正文)的最大持续时间
  writeTimeout: 5000                                         #fasthttp client完整请求写入(包括正文)的最大持续时间
  noDefaultUserAgentHeader: true
  maxConnPerHost: 10000
  MaxIdleConnDuration: 5000                                  #空闲的保持连接将在此持续时间后关闭
  NoDefaultUserAgentHeader: 30000

redis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 1

kafka:
  address: "172.17.101.188:9092"
  topIc: "runnergo"


mongo:
  dsn: "mongodb://runnergo_open:czYNsm6LmfZ0XU3E@172.17.18.255:27017/runnergo_open"
  database: "runnergo_open"
  stressDebugTable: "stress_debug"
  sceneDebugTable: "scene_debug"
  apiDebugTable: "api_debug"
  debugTable: "debug_status"
  autoTable: "auto_report"



machine:
  maxGoroutines: 20005
  serverType: 1
  netName: ""
  diskName: ""


log:
  path: "/data/logs/RunnerGo/RunnerGo-engine-info.log"         #本服务log存放地址


management:
  notifyStopStress: "https://manager.runnergo.cc/management/api/v1/plan/notify_stop_stress"                          #management服务停止性能任务接口
  notifyRunFinish: "https://manager.runnergo.cc/management/api/v1/auto_plan/notify_run_finish"                           #management服务任务完成接口